Add pre commit format
Jim-Hodapp-Coaching/ambi pull request #15
Opened 2022-03-09 15:47 UTC by Serneum

2022-03-09 16:08 UTC, jhodapp requested changes
@Serneum This doesn't seem to work for me just yet. I added an echo statement into `scripts/git/pre-commit` and I never see it print to stdout (which it should). I also made some egregious formatting changes to the source code, and they aren't getting correct when I git add/commit but they definitely do when I manually run `mix format`.

And I definitely ran `./script/create-git-hooks` first and verified that the symlinks exist in ./git

2022-03-09 18:20 UTC, Serneum commented
Huh, yeah. Weird
```
❯ cat .git/hooks/pre-commit
[bat error]: '.git/hooks/pre-commit': No such file or directory (os error 2)
❯ ls -al .git/hooks/pre-commit
lrwxr-xr-x 21 crees  9 Mar 13:16 .git/hooks/pre-commit -> scripts/hooks-wrapper
```

2022-03-09 18:33 UTC, Serneum commented
@jhodapp this should work now. It was an issue with the pathing when setting up the symlinks. I just stole what was used to get the hooks directory and used that. I will add a note in the file itself to list the changes, per the license

2022-03-09 18:40 UTC, Serneum commented
Nevermind. My changes aren't being pushed...likely because of a hook?

2022-03-09 18:49 UTC, Serneum commented
Changed how we add files per [How to git add only files that have already been staged](https://stacktoheap.com/blog/2016/01/02/git-add-only-files-already-staged/)

2022-03-10 14:53 UTC, jhodapp commented
Cool, I'll give this another try here shortly. Thanks!

2022-03-10 15:14 UTC, jhodapp approved these changes
This works great, made some crazy formatting changes locally, committed, and all was formatted sanely again. Nicely done!

2022-03-20 22:24 UTC, Serneum commented
@wumbabum let me know if this looks good to you

2022-03-24 23:50 UTC, jhodapp commented
@Serneum let's go ahead and merge this as-is, Joe's in a pretty busy period right now and I don't think he'll be able to get to reviewing this any time soon.

2022-03-25 00:33 UTC, merged